image: alpine

pages:
  stage: deploy
  script:
  - echo "deploying to gitlab pages..."
  - sed -i "s/%SPREADSHEET_ID%/$SPREADSHEET_ID/" static/checkin.js
  - sed -i "s/%CLIENT_ID%/$CLIENT_ID/" static/checkin.js
  - sed -i "s/%API_KEY%/$API_KEY/" static/checkin.js
  - mv static public
  artifacts:
    paths:
    - public
  environment:
    name: live
  only:
  - master
